M48
; DRILL file KiCad 10.0.1 date 2026-05-05T15:25:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T15:25:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X71.069Y-26.067
X76.849Y-26.067
T2
X77.91Y-52.294
X77.91Y-55.294
M30
